import Link from "next/link";
import {CrmShell} from "@/components/crm-shell";
import {AutomationEditor} from "@/components/automation-editor";
import {requireAdmin} from "@/lib/auth";
import {prisma} from "@/lib/prisma";
import {discardDraft} from "./actions";
export const dynamic="force-dynamic";
export default async function Automations(){
  await requireAdmin();const [rules,runs,categories]=await Promise.all([prisma.automationRule.findMany({orderBy:{createdAt:"desc"}}),prisma.automationRun.findMany({take:50,orderBy:{createdAt:"desc"},include:{rule:true,customer:{include:{conversations:{take:1,orderBy:{updatedAt:"desc"}}}}}}),prisma.product.findMany({where:{category:{not:null}},distinct:["category"],select:{category:true}})]);
  const names=categories.map(c=>c.category!);
  return <CrmShell active="/automatizaciones"><header className="topbar"><div><p className="eyebrow">Reglas del CRM</p><h1>Automatizaciones</h1><p>Reglas sobre futuros ingresos o cambios reales de etapa, tanto manuales como del bot.</p></div></header><section className="panel automation-system-rule"><div><span className="badge success">Programada</span><h2>Seguimiento sin respuesta · 12 h</h2><p>Envía “¡Hola! ¿Seguís interesado?” una sola vez, 12 horas después de nuestro último mensaje si el cliente no respondió.</p></div><dl><div><dt>Horario</dt><dd>Lunes a viernes · 8 a 18 h</dd></div><div><dt>Ventana</dt><dd>Solo WhatsApp vigente</dd></div><div><dt>Excluye</dt><dd>Envío, retiro, finalizado y abandonado</dd></div></dl><p className="muted">Se ejecuta cada hora y vuelve a validar la conversación antes de enviar. Requiere <code>CRON_SECRET</code> configurado en Vercel.</p></section><section className="panel"><h2>Reglas con revisión humana</h2><p>Estas reglas crean tareas o borradores, nunca envían mensajes automáticamente. Los borradores se revisan y se envían individualmente desde el chat, con el bot pausado y dentro de las 24 horas. El envío de plantillas no está habilitado.</p><p>Sin ejecución retroactiva. Reingresar a una etapa vuelve a ejecutar sus reglas activas. Las tareas se asignan al responsable del lead; si no tiene, quedan sin asignar. El vencimiento se calcula desde el cambio de etapa.</p></section><AutomationEditor categories={names}/>{rules.map(r=><AutomationEditor key={`${r.id}-${r.updatedAt.toISOString()}`} rule={r} categories={names}/>)}<section className="panel"><h2>Últimas 50 ejecuciones de reglas con revisión</h2>{runs.length?runs.map(r=><article className="context-note" key={r.id}><strong>{r.rule.name} · {r.customer.fullName||r.customer.whatsappProfileName||r.customer.phone||"Cliente"}</strong><p>{r.content}</p><p>{r.status==="DRAFT"?"Borrador pendiente, no enviado":r.status==="TASK_CREATED"?"Tarea creada":r.status==="DISCARDED"?"Descartado":r.status}</p><small>{r.createdAt.toLocaleString("es-AR",{timeZone:"America/Buenos_Aires",hourCycle:"h23"})}</small><Link href={`/embudo?lead=${r.customerId}`}>Abrir lead</Link>{r.status==="DRAFT"&&r.customer.conversations[0]&&<Link className="button secondary" href={`/bandeja?conversation=${r.customer.conversations[0].id}&draft=${r.id}`}>Revisar mensaje en chat</Link>}{r.status==="DRAFT"&&<form action={discardDraft.bind(null,r.id)}><button className="button secondary">Descartar borrador</button></form>}</article>):<p>Todavía no hay ejecuciones. Las reglas nuevas quedan desactivadas.</p>}</section></CrmShell>;
}
