import Link from "next/link";
import { notFound } from "next/navigation";
import { CrmShell } from "@/components/crm-shell";
import { OrderStatusActions } from "@/components/order-status-actions";
import { prisma } from "@/lib/prisma";
import { formatArs, LOCAL_ADDRESS } from "@/lib/sales-policy";

export const dynamic = "force-dynamic";

const statusLabels: Record<string, string> = { DRAFT: "Borrador", AWAITING_CUSTOMER_CONFIRMATION: "Esperando confirmación", PENDING_REVIEW: "Para revisar", APPROVED_FOR_LOGISTICS: "Aprobado para logística", PREPARING: "En preparación", SHIPPED: "En reparto", DELIVERED: "Entregado", CANCELLED: "Cancelado" };
const paymentLabels: Record<string, string> = { CASH_OR_TRANSFER: "Efectivo o transferencia", CARD_ONE_PAYMENT: "Tarjeta en un pago" };

export default async function OrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const order = await prisma.order.findUnique({ where: { id }, include: { customer: true, items: { include: { product: true } }, activities: { orderBy: { createdAt: "desc" } } } });
  if (!order) notFound();
  const isPickup = order.deliveryMethod === "PICKUP";
  const productCents = order.items.reduce((total, item) => total + item.unitPriceCents * item.quantity, 0);
  return <CrmShell active="/pedidos"><header className="topbar"><div><p className="eyebrow">Venta #{order.saleNumber}</p><h1>{order.recipientName || order.customer.fullName || "Pedido sin nombre"}</h1><p className="topbar-copy">Venta: {order.saleDate.toLocaleString("es-AR")} · Entrega: {order.deliveryDate?.toLocaleDateString("es-AR") ?? "A programar"}</p></div><div className="topbar-actions"><Link className="button secondary" href="/pedidos">Volver a pedidos</Link><OrderStatusActions id={order.id} status={order.status} /></div></header>
    <section className="order-detail-grid"><article className="panel detail-panel"><div className="detail-title"><h2>Estado operativo</h2><span className={`badge ${order.status === "PENDING_REVIEW" ? "warning" : "neutral"}`}>{statusLabels[order.status]}</span></div><dl className="detail-list"><div><dt>Revisión</dt><dd>{order.reviewedAt ? `Validado el ${order.reviewedAt.toLocaleString("es-AR")}` : order.riskReview ? "Requiere revisión manual" : "Pendiente"}</dd></div><div><dt>Riesgo</dt><dd>{order.riskReview ? (order.reviewReason || "Verificar antes de pasar a logística") : "Sin alerta activa"}</dd></div><div><dt>Fecha solicitada</dt><dd>{order.requestedDate?.toLocaleDateString("es-AR") ?? "A coordinar"}</dd></div></dl></article><article className="panel detail-panel"><h2>Entrega y logística</h2><dl className="detail-list"><div><dt>Modalidad</dt><dd>{isPickup ? "Retiro en Av. Cramer" : "Mensajería privada"}</dd></div><div><dt>Destino</dt><dd>{isPickup ? LOCAL_ADDRESS : `${order.deliveryAddress}, ${order.locality}${order.postalCode ? ` · CP ${order.postalCode}` : ""}`}</dd></div><div><dt>Cadete / responsable</dt><dd>{order.assignedCourier ?? "Sin asignar"}</dd></div><div><dt>Franja</dt><dd>{order.deliveryTimeWindow ?? (isPickup ? "Horario de local" : "A coordinar")}</dd></div></dl>{order.logisticsNote ? <div className="context-note"><small>Nota logística</small><p>{order.logisticsNote}</p></div> : null}</article><article className="panel detail-panel"><h2>Cliente y pago</h2><dl className="detail-list"><div><dt>Cliente</dt><dd><Link className="table-primary-link" href={`/clientes/${order.customer.id}`}>{order.customer.fullName ?? order.recipientName}</Link></dd></div><div><dt>Teléfono</dt><dd>{order.customer.phone ?? "Pendiente"}</dd></div><div><dt>Pago</dt><dd>{paymentLabels[order.paymentMethod] ?? order.paymentMethod}</dd></div></dl></article><article className="panel detail-panel"><h2>Total</h2><div className="order-total"><strong>{formatArs(order.totalCents)}</strong><span>Importe a cobrar</span></div><dl className="detail-list compact-details"><div><dt>Productos</dt><dd>{formatArs(productCents)}</dd></div><div><dt>Envío</dt><dd>{formatArs(order.shippingCents)}</dd></div></dl></article></section>
    <section className="section-heading"><h2>Productos</h2></section><section className="panel detail-panel"><div className="order-items">{order.items.map((item) => <div key={item.id}><span><strong>{item.product.name}</strong><small>{item.product.sku} · Cantidad: {item.quantity}</small></span><b>{formatArs(item.unitPriceCents * item.quantity)}</b></div>)}</div></section>
    <section className="section-heading"><h2>Historial</h2></section><section className="panel detail-panel">{order.activities.length ? <div className="order-timeline">{order.activities.map((activity) => <div key={activity.id}><i /><span><strong>{activity.action === "STATUS_CHANGED" ? "Cambio de estado" : "Actualización operativa"}</strong><p>{activity.detail ?? "Sin detalle"}</p><small>{activity.createdAt.toLocaleString("es-AR")}</small></span></div>)}</div> : <div className="empty">No hay acciones registradas todavía. Los próximos cambios de estado y logística quedarán guardados acá.</div>}</section>
  </CrmShell>;
}
