"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createLeadTask, deleteCustomer, updateLeadDetails } from "@/app/clientes/actions";

type LeadDetails = { id: string; updatedAt: string; fullName: string | null; email: string | null; interestCategories: string[]; deliveryAddress: string | null; locality: string | null; postalCode: string | null; deliveryPreference: string | null; notes: string | null; funnelNote: string | null };
export function LeadDetailsEditor({ lead, onSaved }: { lead: LeadDetails; onSaved: () => void }) {
  const original = { fullName: lead.fullName || "", email: lead.email || "", interests: lead.interestCategories.join(", "), deliveryAddress: lead.deliveryAddress || "", locality: lead.locality || "", postalCode: lead.postalCode || "", deliveryPreference: lead.deliveryPreference === "PICKUP" || lead.deliveryPreference === "COURIER" ? lead.deliveryPreference : "", notes: lead.notes || "", funnelNote: lead.funnelNote || "" };
  const [values, setValues] = useState(original), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const dirty = JSON.stringify(values) !== JSON.stringify(original);
  const set = (key: keyof typeof values, value: string) => setValues(current => ({ ...current, [key]: value }));
  return <form className="lead-details-editor" onSubmit={async event => { event.preventDefault(); if (busy || !dirty) return; setBusy(true); setMessage(""); try { const result = await updateLeadDetails({ id: lead.id, expected: lead.updatedAt, ...values }); setMessage(result.message); if (result.ok) onSaved(); } catch { setMessage("No se pudo confirmar el guardado."); } finally { setBusy(false); } }}>
    <label>Nombre<input value={values.fullName} maxLength={120} onChange={event => set("fullName", event.target.value)} /></label><label>Email<input type="email" value={values.email} maxLength={200} onChange={event => set("email", event.target.value)} /></label><label>Intereses<input value={values.interests} placeholder="Separados por coma" maxLength={500} onChange={event => set("interests", event.target.value)} /></label><label>Dirección<input value={values.deliveryAddress} maxLength={300} onChange={event => set("deliveryAddress", event.target.value)} /></label><label>Localidad<input value={values.locality} maxLength={120} onChange={event => set("locality", event.target.value)} /></label><label>Código postal<input value={values.postalCode} maxLength={20} onChange={event => set("postalCode", event.target.value)} /></label><label>Modalidad<select value={values.deliveryPreference} onChange={event => set("deliveryPreference", event.target.value)}><option value="">Sin definir</option><option value="COURIER">Mensajería privada</option><option value="PICKUP">Retiro en local</option></select></label><label className="wide">Notas<textarea value={values.notes} rows={2} maxLength={1000} onChange={event => set("notes", event.target.value)} /></label><label className="wide">Nota comercial<textarea value={values.funnelNote} rows={2} maxLength={1000} onChange={event => set("funnelNote", event.target.value)} /></label><div className="lead-details-save"><button className="button" disabled={busy || !dirty}>{busy ? "Guardando…" : "Guardar cambios"}</button><p role="status">{message}</p></div>
  </form>;
}

export function DeleteCustomerButton({ id, updatedAt }: { id: string; updatedAt: string }) {
  const [open, setOpen] = useState(false), [confirmation, setConfirmation] = useState(""), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const router = useRouter();
  return <section><button className="button secondary" onClick={() => setOpen(!open)} disabled={busy}>Eliminar cliente</button>{open && <form onSubmit={async e => { e.preventDefault(); if (busy) return; setBusy(true); try { const r = await deleteCustomer({ id, confirmation, updatedAt }); setMessage(r.message); if(r.ok) { router.push("/clientes"); router.refresh(); } } catch { setMessage("No se pudo eliminar. Revisá tu sesión."); } finally { setBusy(false); } }}><p>Eliminación definitiva de esta ficha, conversaciones guardadas en el CRM, notas, atribuciones y tareas finalizadas. No borra mensajes en Botpress ni bloquea WhatsApp: si vuelve a escribir, la ficha puede crearse nuevamente. No se permite con pedidos o tareas pendientes. Pausá primero el bot en sus chats.</p><label>Escribí ELIMINAR<input value={confirmation} onChange={e => setConfirmation(e.target.value)} disabled={busy} /></label><button className="button" disabled={busy || confirmation !== "ELIMINAR"}>{busy ? "Eliminando…" : "Eliminar definitivamente"}</button><button type="button" className="button secondary" disabled={busy} onClick={() => { setOpen(false); setConfirmation(""); }}>Cancelar</button></form>}<p role="status">{message}</p></section>;
}

export function LeadTaskForm({ customerId, members, currentUserId, onSaved }: { onSaved?: () => void; customerId: string; members: { id: string; name: string }[]; currentUserId: string }) {
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(""); const router = useRouter();
  return <form className="lead-task-form" onSubmit={async e => { e.preventDefault(); if(busy) return; const form = e.currentTarget; const data = new FormData(form); setBusy(true); try { const date = String(data.get("dueAt") || ""); const r = await createLeadTask({ customerId, title: String(data.get("title")), description: String(data.get("description") || ""), assigneeId: String(data.get("assigneeId")), dueAt: date ? new Date(`${date}:00-03:00`).toISOString() : "" }); setMessage(r.message); if(r.ok) { form.reset(); if (onSaved) onSaved(); else router.refresh(); } } catch { setMessage("No se pudo guardar la tarea. Revisá los datos y tu sesión."); } finally { setBusy(false); } }}>
    <label>Tarea<input name="title" required minLength={3} maxLength={180} /></label><label>Detalle<textarea name="description" maxLength={1000} rows={2} /></label><label>Asignar a<select name="assigneeId" defaultValue={currentUserId} required>{members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Vencimiento (hora Argentina)<input name="dueAt" type="datetime-local" /></label><button className="button" disabled={busy}>{busy ? "Guardando…" : "Crear tarea"}</button><p role="status">{message}</p>
  </form>;
}
