"use client";
import { LeadOwner, LeadTaskEditor } from "./lead-team";
import { useState } from "react";
import type { LeadDetail } from "@/lib/lead-detail";
import Link from "next/link";
import { ConversationChat } from "@/app/bandeja/conversation-chat";
import { InboxPreloader } from "@/app/bandeja/inbox-preloader";
import { parseInboxSnapshot } from "@/lib/inbox-cache";
import { LeadTaskForm, DeleteCustomerButton } from "./lead-actions";
import { funnelStages } from "@/lib/funnel-stages";
import { formatArs } from "@/lib/sales-policy";
import { orderStatusLabel } from "@/lib/order-status";

export function LeadWorkspace({ data, conversationId, onRefresh }: { data: LeadDetail; conversationId?: string; onRefresh: () => void }) {
  const { customer, members, user } = data;
  const id = customer.id;
  const [selectedId, setSelectedId] = useState(conversationId);
  const selected = customer.conversations.find(c => c.id === selectedId) || customer.conversations[0];
  const summary = { "Nombre de WhatsApp": customer.whatsappProfileName, "Teléfono": customer.phone, "WhatsApp ID": customer.whatsappId, "Email": customer.email, "Etapa": funnelStages.find(([stage]) => stage === customer.funnelStage)?.[1], "Intereses": customer.interestCategories.join(", "), "Dirección": customer.deliveryAddress, "Localidad": customer.locality, "Código postal": customer.postalCode, "Modalidad": customer.deliveryPreference === "PICKUP" ? "Retiro en local" : customer.deliveryPreference, "Notas": customer.notes, "Nota comercial": customer.funnelNote };
  return <div className="lead-workspace lead-workspace-columns">
    <section className="panel lead-profile-panel"><h2>{customer.fullName || customer.whatsappProfileName || "Contacto sin nombre"}</h2><dl className="detail-list">{Object.entries(summary).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || "Sin datos"}</dd></div>)}</dl><LeadOwner id={id} assigneeId={customer.assigneeId} members={members} onSaved={onRefresh} /><Link href={`/clientes/${id}`}>Abrir ficha completa</Link><h3>Pedidos</h3>{customer.orders.length ? customer.orders.map(order => <p key={order.id}><Link href={`/pedidos/${order.id}`}>Venta #{order.saleNumber}</Link> · {formatArs(order.totalCents)} · {orderStatusLabel(order.status, order.deliveryMethod)}</p>) : <p>Sin pedidos.</p>}<h3>Origen comercial</h3>{customer.attributions.map(attribution => <p key={attribution.id}>{[attribution.source, attribution.campaignName || attribution.utmCampaign, attribution.adName].filter(Boolean).join(" · ") || "Origen sin identificar"}</p>)}{user.role === "ADMIN" ? <DeleteCustomerButton id={id} updatedAt={customer.updatedAt} /> : null}</section>
    <section className="panel lead-chat">{selected ? <><InboxPreloader refreshPage={false} key={selected.id} conversations={[{ id: selected.id, profileName: customer.whatsappProfileName }]} initial={(() => { const snapshot = parseInboxSnapshot(selected.messageCache?.payload); return snapshot ? { [selected.id]: snapshot } : {}; })()}><ConversationChat compactLead refreshPage={false} key={selected.id} id={selected.id} initialPaused={selected.botPaused} channel={selected.channel} leadConversationPicker={<nav className="lead-conversation-switch" aria-label="Elegir conversación">{customer.conversations.map((conversation, index) => <button key={conversation.id} type="button" onClick={() => setSelectedId(conversation.id)} className={selected.id === conversation.id ? "active" : ""}>{conversation.channel} · {index + 1}</button>)}</nav>} /></InboxPreloader><Link className="button secondary" href={`/pedidos/nuevo?conversation=${selected.id}`}>Crear pedido desde este chat</Link></> : <><div className="lead-empty-title"><h2>Conversación</h2><span className="bot-state-icon paused" role="img" aria-label="Sin conversación">🤖̸</span></div><p>Este cliente no tiene conversaciones vinculadas.</p></>}</section>
    <section className="panel lead-tasks-panel"><h2>Tareas del lead</h2><details className="lead-task-create"><summary className="button">Nueva tarea</summary><LeadTaskForm customerId={id} members={members.map(member => ({ id: member.id, name: member.displayName || member.email }))} currentUserId={user.id} onSaved={onRefresh} /></details><div className="lead-task-list">{customer.tasks.length ? customer.tasks.map(task => <article key={task.id} className="context-note"><strong>{task.title}</strong><p>{task.description}</p><small>{task.assignee?.displayName || task.assignee?.email || "Sin asignar"} · {task.status} {task.dueAt ? `· ${new Date(task.dueAt).toLocaleString("es-AR", { timeZone: "America/Buenos_Aires", hourCycle: "h23" })}` : ""}</small><p>{task.dueAt && ["OPEN", "IN_PROGRESS"].includes(task.status) ? Date.parse(task.dueAt) < Date.now() ? "Tarea vencida" : "Próximo vencimiento" : ""}</p><details><summary>Gestionar tarea</summary><LeadTaskEditor task={task} members={members} onSaved={onRefresh} /></details></article>) : <p className="muted">No hay tareas asociadas.</p>}</div><Link href={`/tareas?customer=${id}`}>Gestionar tareas</Link></section>
  </div>;
}
