"use client";
import { LeadOwner, LeadTaskEditor } from "./lead-team";
import { useMemo, useState } from "react";
import type { LeadDetail } from "@/lib/lead-detail";
import Link from "next/link";
import { ConversationChat } from "@/app/bandeja/conversation-chat";
import { InboxPreloader } from "@/app/bandeja/inbox-preloader";
import { parseInboxSnapshot } from "@/lib/inbox-cache";
import { LeadTaskForm, DeleteCustomerButton } from "./lead-actions";
import { funnelStages } from "@/lib/funnel-stages";
import { formatArs } from "@/lib/sales-policy";
import { orderStatusLabel } from "@/lib/order-status";

export function LeadWorkspace({ data, conversationId, onRefresh }: { data: LeadDetail; conversationId?: string; onRefresh: () => void }) {
  const { customer, members, user } = data;
  const id = customer.id;
  const [selectedId, setSelectedId] = useState(conversationId);
  const [tab, setTab] = useState<"summary" | "conversation" | "tasks" | "orders" | "data">("summary");
  const selected = customer.conversations.find(c => c.id === selectedId) || customer.conversations[0];
  const taskGroups = useMemo(() => ({ active: customer.tasks.filter(task => ["OPEN", "IN_PROGRESS"].includes(task.status)), closed: customer.tasks.filter(task => ["DONE", "CANCELLED"].includes(task.status)) }), [customer.tasks]);
  const lastActivity = selected?.updatedAt ? new Date(selected.updatedAt) : null;
  const relativeActivity = lastActivity ? (() => { const minutes = Math.max(0, Math.floor((Date.now() - lastActivity.getTime()) / 60000)); return minutes < 60 ? `Hace ${minutes || 1} min` : minutes < 1440 ? `Hace ${Math.floor(minutes / 60)} h` : `Hace ${Math.floor(minutes / 1440)} d`; })() : "Sin mensajes";
  const tabs: { id: typeof tab; label: string; count?: number }[] = [{ id: "summary", label: "Resumen" }, { id: "conversation", label: "Conversación" }, { id: "tasks", label: "Tareas", count: taskGroups.active.length }, { id: "orders", label: "Pedidos", count: customer.orders.length }, { id: "data", label: "Datos" }];
  const show = (next: typeof tab) => { setTab(next); requestAnimationFrame(() => document.querySelector(".lead-dialog-body")?.scrollTo({ top: 0 })); };
  const TaskList = ({ tasks, empty }: { tasks: typeof customer.tasks; empty: string }) => tasks.length ? <div className="lead-task-list">{tasks.map(t => <article key={t.id} className="lead-task-card"><div><strong>{t.title}</strong>{t.description ? <p>{t.description}</p> : null}<small>{t.assignee?.displayName || t.assignee?.email || "Sin asignar"} · {t.dueAt ? new Date(t.dueAt).toLocaleString("es-AR", { timeZone: "America/Buenos_Aires", hourCycle: "h23" }) : "Sin vencimiento"}</small></div><span className={`badge ${t.status === "OPEN" ? "warning" : "neutral"}`}>{t.status === "OPEN" ? "Pendiente" : t.status === "IN_PROGRESS" ? "En curso" : t.status === "DONE" ? "Completada" : "Cancelada"}</span><details><summary>Gestionar</summary><LeadTaskEditor task={t} members={members} onSaved={onRefresh} /></details></article>)}</div> : <p className="muted">{empty}</p>;
  return <div className="lead-workspace"><header className="lead-summary-header"><div><h2>{customer.fullName || customer.whatsappProfileName || "Contacto sin nombre"}</h2><p>{customer.phone || "Teléfono por identificar"} · {funnelStages.find(([s]) => s === customer.funnelStage)?.[1] || "Sin etapa"}</p></div><Link className="button secondary" href={`/clientes/${id}`}>Abrir ficha completa</Link></header><nav className="lead-tabs" role="tablist" aria-label="Secciones de la ficha">{tabs.map(item => <button key={item.id} type="button" role="tab" aria-selected={tab === item.id} className={tab === item.id ? "active" : ""} onClick={() => show(item.id)}>{item.label}{item.count !== undefined ? <span>{item.count}</span> : null}</button>)}</nav>
    {tab === "summary" ? <section className="lead-tab-content lead-overview" role="tabpanel"><div className="lead-overview-grid"><article><span>Etapa</span><strong>{funnelStages.find(([s]) => s === customer.funnelStage)?.[1] || "Sin etapa"}</strong></article><article><span>Responsable</span><strong>{members.find(member => member.id === customer.assigneeId)?.displayName || members.find(member => member.id === customer.assigneeId)?.email || "Sin asignar"}</strong></article><article><span>Intereses</span><strong>{customer.interestCategories.join(", ") || "Sin clasificar"}</strong></article><article><span>Modalidad</span><strong>{customer.deliveryPreference === "PICKUP" ? "Retiro en local" : customer.deliveryPreference || "Sin definir"}</strong></article><article><span>Localidad</span><strong>{customer.locality || "Sin datos"}</strong></article><article><span>Último mensaje</span><strong>{relativeActivity}</strong><small>{selected?.botPaused ? "Bot pausado · atención manual" : "Bot activo"}</small></article><article><span>Tareas activas</span><strong>{taskGroups.active.length}</strong></article><article><span>Pedidos asociados</span><strong>{customer.orders.length}</strong></article></div><div className="lead-alerts">{selected?.botPaused ? <p className="badge warning">Bot pausado: requiere atención manual</p> : null}{taskGroups.active.some(task => task.dueAt && Date.parse(task.dueAt) < Date.now()) ? <p className="badge warning">Hay tareas vencidas</p> : null}{customer.funnelNote ? <p><strong>Alerta comercial:</strong> {customer.funnelNote}</p> : null}{selected?.updatedAt ? <p><strong>Último mensaje:</strong> {new Date(selected.updatedAt).toLocaleString("es-AR", { timeZone: "America/Buenos_Aires", hourCycle: "h23" })}</p> : null}</div><div className="lead-owner-compact"><LeadOwner id={id} assigneeId={customer.assigneeId} members={members} onSaved={onRefresh} /></div></section> : null}
    {tab === "conversation" ? <section className="lead-tab-content lead-chat" role="tabpanel"><h3>Conversación</h3>{selected ? <><nav className="lead-conversation-switch">{customer.conversations.map((c, i) => <button key={c.id} type="button" onClick={() => setSelectedId(c.id)} className={selected.id === c.id ? "active" : ""}>{c.channel} · {i + 1}</button>)}</nav><InboxPreloader refreshPage={false} key={selected.id} conversations={[{ id: selected.id, profileName: customer.whatsappProfileName }]} initial={(() => { const snapshot = parseInboxSnapshot(selected.messageCache?.payload); return snapshot ? { [selected.id]: snapshot } : {}; })()}><ConversationChat compactLead refreshPage={false} key={selected.id} id={selected.id} initialPaused={selected.botPaused} channel={selected.channel} /></InboxPreloader><Link className="button secondary" href={`/pedidos/nuevo?conversation=${selected.id}`}>Crear pedido desde este chat</Link></> : <p>Este cliente no tiene conversaciones vinculadas.</p>}</section> : null}
    {tab === "tasks" ? <section className="lead-tab-content" role="tabpanel"><div className="section-heading"><div><h3>Tareas activas</h3><p className="muted">Creá y gestioná el seguimiento sin perder el contexto del lead.</p></div></div><details className="lead-task-create"><summary className="button">Nueva tarea</summary><LeadTaskForm customerId={id} members={members.map(m => ({ id: m.id, name: m.displayName || m.email }))} currentUserId={user.id} onSaved={onRefresh} /></details><TaskList tasks={taskGroups.active} empty="No hay tareas activas." /><h3 className="lead-subheading">Finalizadas</h3><TaskList tasks={taskGroups.closed} empty="Todavía no hay tareas finalizadas." /><Link href={`/tareas?customer=${id}`}>Ver todas las tareas de este cliente</Link></section> : null}
    {tab === "orders" ? <section className="lead-tab-content" role="tabpanel"><h3>Pedidos asociados</h3>{customer.orders.length ? <div className="lead-order-list">{customer.orders.map(order => <Link key={order.id} href={`/pedidos/${order.id}`}><strong>Venta #{order.saleNumber}</strong><span>{orderStatusLabel(order.status, order.deliveryMethod)}</span><span>{order.deliveryMethod === "PICKUP" ? "Retiro en local" : "Mensajería"}</span><b>{formatArs(order.totalCents)}</b></Link>)}</div> : <p className="muted">Este cliente todavía no tiene pedidos asociados.</p>}</section> : null}
    {tab === "data" ? <section className="lead-tab-content" role="tabpanel"><h3>Datos completos</h3><dl className="detail-list lead-data-list">{Object.entries({ "Nombre de WhatsApp": customer.whatsappProfileName, "Teléfono": customer.phone, "WhatsApp ID": customer.whatsappId, "Email": customer.email, "Dirección": customer.deliveryAddress, "Localidad": customer.locality, "Código postal": customer.postalCode, "Notas": customer.notes, "Nota comercial": customer.funnelNote, "Origen": customer.attributions.map(a => [a.source, a.campaignName || a.utmCampaign, a.adName].filter(Boolean).join(" · ")).filter(Boolean).join(" / ") }).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || "Sin datos"}</dd></div>)}</dl>{user.role === "ADMIN" ? <DeleteCustomerButton id={id} updatedAt={customer.updatedAt} /> : null}</section> : null}</div>;
}
