import { CrmShell } from "@/components/crm-shell";
import { TaskActions } from "@/components/task-actions";
import { createTask } from "@/app/tareas/actions";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

const labels: Record<string, string> = { FOLLOW_UP: "Seguimiento", DELIVERY_CONFIRMATION: "Confirmar entrega", ORDER_REVIEW: "Revisar pedido", LOGISTICS: "Logística", OTHER: "General" };
const statusLabels: Record<string, string> = { OPEN: "Pendiente", IN_PROGRESS: "En curso", DONE: "Completada", CANCELLED: "Cancelada" };

export default async function TasksPage() {
  const [tasks, customers, orders, users] = await Promise.all([prisma.task.findMany({ take: 80, orderBy: [{ status: "asc" }, { dueAt: "asc" }, { createdAt: "desc" }], include: { customer: true, order: true, assignee: true } }), prisma.customer.findMany({ take: 80, orderBy: { updatedAt: "desc" }, select: { id: true, fullName: true, phone: true } }), prisma.order.findMany({ take: 80, orderBy: { createdAt: "desc" }, include: { customer: true } }), prisma.userProfile.findMany({ where: { isActive: true }, orderBy: { email: "asc" } })]);
  return <CrmShell active="/tareas"><header className="topbar"><div><p className="eyebrow">Operación</p><h1>Tareas</h1><p className="topbar-copy">Seguimientos, validaciones y entregas asignados al equipo.</p></div></header>
    <section className="task-create panel"><h2>Nueva tarea</h2><form action={createTask} className="task-form"><label>Tarea<input name="title" required placeholder="Ej.: confirmar disponibilidad para mañana" /></label><label>Tipo<select name="type" defaultValue="FOLLOW_UP">{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Vencimiento<input name="dueAt" type="datetime-local" /></label><label>Asignar a<select name="assigneeId"><option value="">A mí</option>{users.map((user) => <option key={user.id} value={user.id}>{user.displayName || user.email}</option>)}</select></label><label>Cliente<select name="customerId"><option value="">Sin vincular</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.fullName || customer.phone || "Contacto sin nombre"}</option>)}</select></label><label>Pedido<select name="orderId"><option value="">Sin vincular</option>{orders.map((order) => <option key={order.id} value={order.id}>{order.recipientName || order.customer.fullName || "Pedido"} · {order.createdAt.toLocaleDateString("es-AR")}</option>)}</select></label><label className="task-description">Detalle<input name="description" placeholder="Contexto interno o próximo paso" /></label><button className="button" type="submit">Crear tarea</button></form></section>
    <section className="section-heading"><h2>Trabajo pendiente</h2><span className="muted">{tasks.filter((task) => task.status !== "DONE" && task.status !== "CANCELLED").length} activas</span></section><section className="panel task-table"><table><thead><tr><th>Tarea</th><th>Vinculada a</th><th>Responsable</th><th>Vencimiento</th><th>Estado</th><th></th></tr></thead><tbody>{tasks.map((task) => <tr key={task.id}><td><strong>{task.title}</strong><small>{labels[task.type]}{task.description ? ` · ${task.description}` : ""}</small></td><td>{task.order ? `Pedido · ${task.order.recipientName}` : task.customer ? task.customer.fullName || task.customer.phone || "Cliente" : "—"}</td><td>{task.assignee?.displayName || task.assignee?.email || "Sin asignar"}</td><td>{task.dueAt ? task.dueAt.toLocaleString("es-AR") : "Sin fecha"}</td><td><span className={`badge ${task.status === "OPEN" ? "warning" : task.status === "DONE" ? "" : "neutral"}`}>{statusLabels[task.status]}</span></td><td><TaskActions id={task.id} status={task.status} /></td></tr>)}</tbody></table>{!tasks.length ? <div className="empty">Todavía no hay tareas. Creá la primera para organizar el seguimiento operativo.</div> : null}</section>
  </CrmShell>;
}
